## Introduction NumPy

In [1]:
import numpy as np

### NumPy array

In [2]:
myList = [1, 3, 5, 7, 9]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([1, 3, 5, 7, 9])

In [5]:
matrixList = [[1, 2, 3], [3, 2, 1], [2, 3, 1]]

In [6]:
matrixList

[[1, 2, 3], [3, 2, 1], [2, 3, 1]]

In [7]:
matrixList[0][1]

2

In [8]:
np.array(matrixList)

array([[1, 2, 3],
       [3, 2, 1],
       [2, 3, 1]])

### arange

In [9]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

### zeros

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace

In [16]:
np.linspace(0, 30, 6)

array([ 0.,  6., 12., 18., 24., 30.])

In [17]:
np.linspace(0, 20, 6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [18]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [19]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### eye

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### random

In [21]:
np.random.randn(5)

array([-0.06972714,  0.47529344,  2.41001767, -0.26185786,  0.30626606])

In [22]:
np.random.randn(3, 3)

array([[-1.87120754, -0.25837103,  1.84485543],
       [-0.62953371, -0.46634382, -2.59638616],
       [-0.66516728, -1.35764091, -1.73804588]])

In [23]:
np.random.randint(2, 8)

3

In [24]:
np.random.randint(2, 1000, 2)

array([ 87, 386])

In [25]:
myRandomArray = np.random.randint(0, 250, 10)

In [26]:
myRandomArray

array([115, 146,  29, 166, 233, 176, 101, 128,  27,  49])

## Array Methods

In [27]:
myNumpyArray = np.arange(25)

In [28]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
myNumpyArray.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
myNumpyArray.max()

24

In [31]:
myNumpyArray.min()

0

In [32]:
myNumpyArray.argmax()

24

In [33]:
myNumpyArray.argmin()

0

In [34]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
reshapemyNumpyArray = myNumpyArray.reshape(5, 5)

In [36]:
reshapemyNumpyArray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Index Operations

In [37]:
ourArray = np.arange(0, 15)

In [38]:
ourArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
ourArray[3]

3

In [40]:
ourArray[0: 14: 2]

array([ 0,  2,  4,  6,  8, 10, 12])

In [41]:
ourArray[3: 5]

array([3, 4])

In [42]:
ourArray[3: 7] = 0

In [43]:
ourArray

array([ 0,  1,  2,  0,  0,  0,  0,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
ourArray[3: 7]

array([0, 0, 0, 0])

In [45]:
yourArray = np.arange(0, 20)

In [46]:
yourArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
slicingArray = yourArray[1: 6]

In [48]:
slicingArray

array([1, 2, 3, 4, 5])

In [49]:
yourArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
type(slicingArray)

numpy.ndarray

In [51]:
slicingArray[:] = 1000

In [52]:
slicingArray

array([1000, 1000, 1000, 1000, 1000])

In [53]:
yourArray

array([   0, 1000, 1000, 1000, 1000, 1000,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [54]:
newArray = np.arange(0, 20)

In [55]:
copyArray = newArray.copy()

In [56]:
newArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
copyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [58]:
copyArraySlicing = copyArray[5: 10]

In [59]:
copyArraySlicing

array([5, 6, 7, 8, 9])

In [60]:
copyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
newArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [62]:
copyArraySlicing[:] = 1000

In [63]:
copyArraySlicing

array([1000, 1000, 1000, 1000, 1000])

In [64]:
copyArray

array([   0,    1,    2,    3,    4, 1000, 1000, 1000, 1000, 1000,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [65]:
newArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Matrix

In [66]:
otherList = [[1, 3, 5], [2, 4, 6], [30, 60, 90]]

In [67]:
otherList = np.array(otherList)

In [68]:
otherList

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [30, 60, 90]])

In [69]:
otherList[0]

array([1, 3, 5])

In [70]:
otherList[0, 0]

1

In [71]:
otherList[0][0]

1

In [72]:
otherList[2:, 2:]

array([[90]])

In [73]:
otherList[2:]

array([[30, 60, 90]])

In [74]:
otherList[:, 2:]

array([[ 5],
       [ 6],
       [90]])

### Matrix Operations

In [75]:
aNewArray = np.random.randint(1, 100, 15)

In [76]:
aNewArray

array([33, 88, 68, 33, 30, 90, 83, 24, 78, 24, 26, 88, 67, 94, 18])

In [77]:
aNewArray < 30

array([False, False, False, False, False, False, False,  True, False,
        True,  True, False, False, False,  True])

In [78]:
aNewArray > 50

array([False,  True,  True, False, False,  True,  True, False,  True,
       False, False,  True,  True,  True, False])

In [79]:
resultArray = aNewArray > 50

In [80]:
aNewArray[resultArray]

array([88, 68, 90, 83, 78, 88, 67, 94])

In [81]:
aNewArray[aNewArray > 50]

array([88, 68, 90, 83, 78, 88, 67, 94])

In [82]:
aNewArray

array([33, 88, 68, 33, 30, 90, 83, 24, 78, 24, 26, 88, 67, 94, 18])

In [84]:
lastArray = np.arange(0, 30)

In [85]:
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
lastArray + lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [87]:
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [88]:
lastArray - lastArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
lastArray * lastArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [90]:
lastArray / lastArray

C:\Users\MBK's EXCALIBUR\AppData\Local\Temp\ipykernel_4844\206178132.py:1: RuntimeWarning: invalid value encountered in true_divide
  lastArray / lastArray


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [91]:
np.sqrt(lastArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])